const BY_NAME: Record<string, string> = {
  dockerfile: 'dockerfile',
  makefile: 'plaintext',
  jenkinsfile: 'plaintext',
  'docker-compose.yml': 'yaml',
  'docker-compose.yaml': 'yaml',
  'compose.yml': 'yaml',
  'compose.yaml': 'yaml',
  '.gitignore': 'plaintext',
  '.env': 'ini',
  '.env.local': 'ini',
  '.env.example': 'ini'
};

const EXT_TO_LANGUAGE: Record<string, string> = {
  abap: 'abap',
  cls: 'apex',
  azcli: 'azcli',
  bat: 'bat',
  cmd: 'bat',
  bicep: 'bicep',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  edn: 'clojure',
  coffee: 'coffeescript',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  cs: 'csharp',
  csx: 'csharp',
  css: 'css',
  scss: 'scss',
  less: 'less',
  dart: 'dart',
  dockerfile: 'dockerfile',
  ex: 'elixir',
  exs: 'elixir',
  fs: 'fsharp',
  fsx: 'fsharp',
  ftl: 'freemarker2',
  go: 'go',
  graphql: 'graphql',
  gql: 'graphql',
  handlebars: 'handlebars',
  hbs: 'handlebars',
  tf: 'hcl',
  tfvars: 'hcl',
  hcl: 'hcl',
  html: 'html',
  htm: 'html',
  shtml: 'html',
  xhtml: 'html',
  jsp: 'html',
  asp: 'html',
  aspx: 'html',
  vue: 'html',
  svelte: 'html',
  cfm: 'cfml',
  cfc: 'cfml',
  cfml: 'cfml',
  cfs: 'cfml',
  cfr: 'cfml',
  ini: 'ini',
  properties: 'ini',
  toml: 'ini',
  env: 'ini',
  java: 'java',
  jav: 'java',
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  es6: 'javascript',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  jl: 'julia',
  kt: 'kotlin',
  kts: 'kotlin',
  lua: 'lua',
  liquid: 'liquid',
  md: 'markdown',
  markdown: 'markdown',
  mdx: 'mdx',
  m: 'objective-c',
  pas: 'pascal',
  pl: 'perl',
  pm: 'perl',
  php: 'php',
  phtml: 'php',
  php4: 'php',
  php5: 'php',
  ps1: 'powershell',
  psm1: 'powershell',
  proto: 'proto',
  pug: 'pug',
  jade: 'pug',
  py: 'python',
  pyw: 'python',
  r: 'r',
  rmd: 'r',
  cshtml: 'razor',
  rst: 'restructuredtext',
  rb: 'ruby',
  gemspec: 'ruby',
  rs: 'rust',
  scala: 'scala',
  sc: 'scala',
  sbt: 'scala',
  scm: 'scheme',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  sol: 'sol',
  sql: 'sql',
  mysql: 'mysql',
  swift: 'swift',
  tcl: 'tcl',
  twig: 'twig',
  ts: 'typescript',
  tsx: 'typescript',
  cts: 'typescript',
  mts: 'typescript',
  vb: 'vb',
  xml: 'xml',
  xsd: 'xml',
  svg: 'xml',
  xsl: 'xml',
  xslt: 'xml',
  wsdl: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  csv: 'plaintext',
  txt: 'plaintext',
  log: 'plaintext'
};

export function languageForPath(p: string): string {
  const name = p.replace(/\\/g, '/').split('/').pop() ?? p;
  const lower = name.toLowerCase();
  if (BY_NAME[lower]) return BY_NAME[lower];
  const ext = lower.includes('.') ? lower.slice(lower.lastIndexOf('.') + 1) : '';
  return (ext && EXT_TO_LANGUAGE[ext]) || 'plaintext';
}

export function extensionForLanguage(lang: string): string {
  const entry = Object.entries(EXT_TO_LANGUAGE).find(([, v]) => v === lang);
  return entry ? entry[0] : 'txt';
}

export const COMMON_EXTENSIONS = [
  'md',
  'sql',
  'html',
  'cfm',
  'cfc',
  'js',
  'ts',
  'py',
  'json',
  'css',
  'sh',
  'yaml',
  'php',
  'txt'
];
